### ISSUE TITLE
Scientific Validation of Screening Results

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/system-validation#4]
Before we can offer European-level screening as public climate service in CSIS, we have to make sure that it deliver realistic and credible results, of course depending on the quality of available input data ("[RIRO"](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out)). 

"PLINIVS simplified model" for hazards with local effects is now implemented in EMIKAT. The question is whether the calculated results have been has validated / quality assured?

Related issues are:
- [ ] [Please test and if needed calibrate the local temperature estimates ](https://github.com/clarity-h2020/emikat/issues/24)
- [ ] [Tmrt calculation script](https://github.com/clarity-h2020/local-effects/issues/8)

**Note:** This is a showstopper issue for [CSIS Public Release](https://github.com/clarity-h2020/csis/issues/145).

**Comment by DenoBeno** [comment]
Mattia says that the ranges of temperatures are OK now. What needs to be done is the grid-by-grid comparison on some areas, to see if the hot/cold areas are the same in simple model and in more accurate ones.

**Comment by claudiahahn** [comment]
Suggestion: Maybe the mortality results from the emikat calculation could be compared with the UrbanSIS results for Stockholm? @LenaStr what do you think?

**Comment by DenoBeno** [comment]
I find the mortality trends for the "AIT test" study in Vienna very suspect.
The mortality is going down with time, at least for the RCP26.

![image](https://user-images.githubusercontent.com/2961790/78304440-0ece1e00-753f-11ea-8720-dfc8beeec8dc.png)

Unfortunately, the scenario analysis isn't showing RCP45 and RCP85, so I'm not sure if this is something to worry about or not. Isn't the climate supposed to heat up even for RCP26?

![image](https://user-images.githubusercontent.com/2961790/78304745-b3506000-753f-11ea-81d9-800103c4140d.png)

Ah, I see. So RCP26 would start returning back to normal somewhere around 2040. OK, that's consistent with what we get then. Guess this is a good news after all.

**Comment by DenoBeno** [comment]
Please look at this table: https://csis.myclimateservice.eu/study/25/step/3682/view/table

In some areas (probably on a hill) MRT is lower than T_A. 

![image](https://user-images.githubusercontent.com/2961790/78305029-412c4b00-7540-11ea-8738-516e92fc0769.png)

Is this possible? Is this an artifact caused by height correction?

Btw, could someone remind me what is T_A? Is that "ambient" temperature, that is the temperature we would measure in the shadow 2m above ground?

**Comment by RobAndGo** [comment]
@DenoBeno: Regarding T_A, I made a post for you here to answer the same question you had in the following issue:
https://github.com/clarity-h2020/csis/issues/104#issuecomment-607828676

**Comment by RobAndGo** [comment]
And I can't seem to load the table. I am logged into CSIS and am using the latest version of chrome (Version 80.0.3987.162 (Official Build) (64-bit)), but I get this screen:
![image](https://user-images.githubusercontent.com/45385637/78331374-31375a00-7586-11ea-9c5e-0b9606cda74d.png)
It's been like this for the past 5 minutes. Should it take this long? I'm also getting the same view in firefox. 

Is it possible to show the values in your table limited to 2 decimal places?

**Comment by p-a-s-c-a-l** [comment]
> It's been like this for the past 5 minutes. Should it take this long? I'm also getting the same view in firefox.

No. Please try this [direct link](https://csis.myclimateservice.eu/apps/simple-table-component/build/HazardLocalEffectsTable/?host=https://csis.myclimateservice.eu&study_uuid=9359e741-df40-4bcd-9faf-2093b499c65c&study_area=POLYGON((16.317125%2048.250858,16.317125%2048.290538,16.51531%2048.290538,16.51531%2048.250858,16.317125%2048.250858))&emikat_id=3183&datapackage_uuid=2434ce93-93d4-4ca2-8618-a2de768d3f16&write_permissions=1&study_variant=BASELINE&time_period=20710101-21001231&emissions_scenario=rcp85&event_frequency=Frequent) and check if there are any error messages on the debugging console (CTRL+SHIFT+i) and report any bugs [here](https://github.com/clarity-h2020/simple-table-component/issues/new).

> Is it possible to show the values in your table limited to 2 decimal places?

Yes, it's on the [todo list](https://github.com/clarity-h2020/simple-table-component/issues/12).

**Comment by p-a-s-c-a-l** [comment]
> Unfortunately, the scenario analysis isn't showing RCP45 and RCP85, so I'm not sure if this is something to worry about or not.

That's O.K. See [this comment](https://github.com/clarity-h2020/emikat/issues/30#issuecomment-558132510) for an explanation.

**Comment by RobAndGo** [comment]
Thanks @p-a-s-c-a-l! I did what you said and I see the following text:

![image](https://user-images.githubusercontent.com/45385637/78336413-9774aa80-758f-11ea-83e2-0e461e5185dd.png)

Now I thought about the first lines about JavaScript not being enabled, but I checked my settings in chrome and it is indeed enabled:

![image](https://user-images.githubusercontent.com/45385637/78336232-567c9600-758f-11ea-8fcf-b3e0971e58ab.png)

Maybe the CLARITY site has a filter built in to prevent stupid people like me from accessing climate information!  ![lol](https://user-images.githubusercontent.com/45385637/78336823-4dd88f80-7590-11ea-8df0-f07b7d405844.gif)

But looking deeper, under "Console" I did see this as a message:
![image](https://user-images.githubusercontent.com/45385637/78336973-84aea580-7590-11ea-9c23-b89b7bdf6b9a.png)
Perhaps it is just that I am lacking certain permissions?

**Comment by p-a-s-c-a-l** [comment]
> Perhaps it is just that I am lacking certain permissions?

Yes, we are still using an  [ugly workaround](https://github.com/clarity-h2020/docker-drupal/issues/16#issuecomment-524957195) for storing EMIKAT credentials and it seems they were missing in your user profile. I've included them now it should work, please try again.

**Comment by RobAndGo** [comment]
Thank you @p-a-s-c-a-l !! It works now.

**Comment by p-a-s-c-a-l** [comment]
to be continued here: https://github.com/clarity-h2020/emikat/issues/35
